version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: npm test
  publish:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install --production
      - run: npm publish --access public

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - build
      - publish:
          context: qatonic
          requires:
            - build
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
